name: sit_break_app
description: تطبيق تذكير بالجلوس والاستراحة مع كشف حركة تلقائي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.1
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
