dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 # لحفظ الإعدادات واللغة
  sensors_plus: ^5.0.1      # لاستشعار حركة الهاتف
  audioplayers: ^6.0.0      # لتشغيل نغمة المنبه
  screen_state: ^2.1.0      # لمعرفة إذا كانت شاشة الهاتف شغالة
